name: CI - Build and Push Strapi Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/strapi-app
          IMAGE_TAG=${{ github.sha }}
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
          echo "$IMAGE_NAME:$IMAGE_TAG" > image_tag.txt

      - name: Upload image tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: image_tag
          path: image_tag.txt

      - name: Trigger Terraform workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: "CD - Deploy Strapi on EC2"
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
