# .github/workflows/ci.yml
# This version is GUARANTEED to have the artifact upload step.

name: CI - Build & Push Strapi Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/strapi-app:${{ github.sha }}

      # --- THESE ARE THE MISSING STEPS ---
      # Step 1: Create the artifact file that the deployment workflow needs.
      - name: Create image tag artifact
        run: echo ${{ github.sha }} > image_tag.txt

      # Step 2: Upload that file so the next workflow can find and download it.
      - name: Upload image tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: image_tag
          path: image_tag.txt

