# This workflow deploys the Strapi application to an EC2 instance using Terraform.
# It is triggered manually.

name: CD - Deploy Strapi with Terraform

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag to deploy'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Changed to Mumbai region

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="strapi_image_tag=${{ github.event.inputs.image_tag }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="strapi_image_tag=${{ github.event.inputs.image_tag }}"

