name: CD - Deploy Strapi on EC2

on:
  # Manual trigger
  workflow_dispatch:

  # Auto trigger when CI finishes successfully
  workflow_run:
    workflows: ["CI - Build and Push Strapi Image"] # must match ci.yml "name"
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Run if CI succeeded OR if triggered manually
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Download image tag
        uses: actions/download-artifact@v4
        with:
          name: image_tag

      - name: Read image tag
        id: image
        run: echo "tag=$(cat image_tag.txt)" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="image_tag=${{ steps.image.outputs.tag }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="image_tag=${{ steps.image.outputs.tag }}"

      - name: Show EC2 Public IP
        run: terraform output public_ip || echo "⚠️ No public_ip output found"
