name: CD - Deploy Strapi on EC2

on:
  workflow_dispatch:   # Manual trigger still works
  workflow_run:        # Auto trigger after CI
    workflows: ["CI - Build and Push Strapi Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Download image tag
        uses: actions/download-artifact@v4
        with:
          name: image_tag

      - name: Read image tag
        id: image
        run: echo "tag=$(cat image_tag.txt)" >> $GITHUB_OUTPUT

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="image_tag=${{ steps.image.outputs.tag }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="image_tag=${{ steps.image.outputs.tag }}"
