name: CD - Deploy Strapi on EC2

on:
  workflow_dispatch:  # Manual trigger

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.6  # latest stable

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -var="image_tag=latest" \
                           -var="aws_region=ap-south-1"
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="image_tag=latest" \
                                                -var="aws_region=ap-south-1"
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
