name: Deploy to EC2 with Terraform

on:
  workflow_dispatch:

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.0

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Plan
        id: plan
        run: |
          terraform -chdir=terraform plan \
            -var="docker_image_tag=${{ github.sha }}" \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="ec2_key_pair_name=${{ secrets.EC2_KEY_PAIR_NAME }}" \
            -var="security_group_id=${{ secrets.TF_VAR_security_group_id }}" \
            -out=tfplan
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve tfplan

