# .github/workflows/ci.yml
# This is the corrected build workflow.
# It now correctly creates and uploads the artifact needed for deployment.

name: CI - Build & Push Strapi Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          # Using the secret names from your original file
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Using a dynamic tag based on the commit SHA for unique versions
          tags: ${{ secrets.DOCKER_USERNAME }}/strapi-app:${{ github.sha }}

      # --- THIS IS THE CRITICAL FIX ---
      # This step creates the artifact file needed by the deployment workflow
      - name: Create image tag artifact
        run: echo ${{ github.sha }} > image_tag.txt

      # This step uploads the file so the next workflow can download it
      - name: Upload image tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: image_tag
          path: image_tag.txt

